Add PR template
Otus-DevOps-2021-05/vmarkitanov_infra pull request #1
Opened 2021-06-14 15:31 UTC by vmarkitanov

2021-06-14 17:34 UTC, mrgreyves requested changes
Здравствуйте!) К сожалению задание выполнено не корректно, рекомендую повторно свериться с методичкой. ДЗ возвращаю на доработку.

2021-06-16 15:18 UTC, mrgreyves requested changes
Здравствуйте!) Задание выполнено снова не корректно, не хватает workflow для github actions. Рекомендую свериться с методичкой.

2021-06-17 13:17 UTC, vmarkitanov commented
Добавил workflows. Теперь ошибка при проверке скрипта питона выходит. Или так и должно быть?

2021-06-17 18:12 UTC, mrgreyves requested changes
Здравствуйте!) Оставил комментарий к файлу =)

2021-06-17 18:12 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Смотрим внимательно =)

2021-06-18 04:13 UTC, vmarkitanov commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Я в Python мягко сказать "не силен" :), но то что вижу это test_equal всегда вернет false, так как  2 > 1, а не равно.

2021-06-18 05:03 UTC, vmarkitanov commented
Так правильно?

2021-06-18 15:37 UTC, mrgreyves approved these changes
Здравствуйте!) Вот теперь все правильно =)

2021-06-18 16:08 UTC, merged